apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiapp-arm-st
  namespace: aiedge
spec:
  selector:
    matchLabels:
      app: aiapp-arm-st
  replicas: 1
  template:
    metadata:
      labels:
        app: aiapp-arm-st
    spec:
      containers:
      - name: aiapp
        image: david945/aiapp-arm:v10
        imagePullPolicy: IfNotPresent
        env:
          - name: IMG_NUM
            value: "125"
          - name: FPS
            value: "25"
          - name: OBJECTDETECTIONURL
            value: "http://192.168.20.150:30001/v1/face/detection"
          - name: PUSHSTREAM_URL
            value: "rtmp://192.168.20.150:30200/live/stream3"
          - name: EDGE_DEVNAME
            value: "edge1-cam1"
        securityContext:
          privileged: true
        volumeMounts :
        - name: user-volume
          mountPath: "/tmp/aiedge/config/user.json"
          readOnly: true
      volumes:
      - name: user-volume
        secret:
          secretName: userconfig
      nodeSelector:
        kubernetes.io/hostname: edge1-nx40
---
apiVersion: v1
kind: Secret
metadata:
  name: userconfig
type: Opaque
data:
  login.txt: 

